# Generated by Django 5.0.6 on 2024-05-12 00:14

import django.db.models.deletion
import djangoProject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolClass', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[djangoProject.models.validate_age])),
                ('gender', models.CharField(choices=[('М', 'Мальчик'), ('Д', 'Девочка')], max_length=1)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.schoolclasses')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['age', 'gender', 'name'],
            },
        ),
    ]
